trigger:
- none
jobs:
  - job: 'AHL_BrowserStack'
    pool:
      name: 'Default'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: '$Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer'
      displayName: "Install Chrome"

    - script: python -m pip install --upgrade pip && pip --version
      displayName: 'Install/upgrade pip'

    - script: python -m pip install seleniumbase -U && sbase --version
      displayName: 'Verify install from PyPI/Update Seleniumbase'

    - script: seleniumbase install chromedriver latest
      displayName: 'Install chromedriver latest'

    - script: pip install pytest-azurepipelines
      displayName: 'Install Pytest'